/* BucketList AI — 100+ dream idea bank. Categories: travel, adventure, learn, give, create. UMD. */
/* cost/effort: 1 = low, 2 = medium, 3 = high */

var IDEA_CATEGORIES = ["travel", "adventure", "learn", "give", "create"];
var CATEGORY_LABELS = { travel: "Travel", adventure: "Adventure", learn: "Learn", give: "Give", create: "Create" };

var IDEA_BANK = [
  // TRAVEL (21)
  { t: "See the Northern Lights", cat: "travel", cost: 3, effort: 2 },
  { t: "Visit Japan during cherry blossom season", cat: "travel", cost: 3, effort: 2 },
  { t: "Road-trip Route 66", cat: "travel", cost: 2, effort: 2 },
  { t: "Go on safari in Africa", cat: "travel", cost: 3, effort: 2 },
  { t: "Cruise the Mediterranean", cat: "travel", cost: 3, effort: 1 },
  { t: "Backpack through Southeast Asia", cat: "travel", cost: 2, effort: 3 },
  { t: "Stand at the rim of the Grand Canyon", cat: "travel", cost: 2, effort: 1 },
  { t: "See the Eiffel Tower sparkle at night", cat: "travel", cost: 3, effort: 1 },
  { t: "Island-hop in Greece", cat: "travel", cost: 3, effort: 2 },
  { t: "Sleep in an overwater bungalow", cat: "travel", cost: 3, effort: 1 },
  { t: "Hike to Machu Picchu", cat: "travel", cost: 3, effort: 3 },
  { t: "Bathe in Iceland's Blue Lagoon", cat: "travel", cost: 3, effort: 1 },
  { t: "Ride the Trans-Siberian Railway", cat: "travel", cost: 3, effort: 3 },
  { t: "Trek through Patagonia", cat: "travel", cost: 3, effort: 3 },
  { t: "Snorkel the Great Barrier Reef", cat: "travel", cost: 3, effort: 2 },
  { t: "Walk the Great Wall of China", cat: "travel", cost: 3, effort: 2 },
  { t: "Explore Vietnam by motorbike", cat: "travel", cost: 2, effort: 3 },
  { t: "See Iguazu Falls", cat: "travel", cost: 3, effort: 2 },
  { t: "Tour Banff and the Canadian Rockies", cat: "travel", cost: 2, effort: 2 },
  { t: "Drive Italy's Amalfi Coast", cat: "travel", cost: 3, effort: 1 },
  { t: "Tour New Zealand by campervan", cat: "travel", cost: 3, effort: 2 },
  // ADVENTURE (21)
  { t: "Skydive", cat: "adventure", cost: 2, effort: 2 },
  { t: "Bungee jump", cat: "adventure", cost: 2, effort: 2 },
  { t: "Get scuba certified", cat: "adventure", cost: 2, effort: 2 },
  { t: "Ride in a hot-air balloon", cat: "adventure", cost: 2, effort: 1 },
  { t: "Go white-water rafting", cat: "adventure", cost: 2, effort: 2 },
  { t: "Try paragliding", cat: "adventure", cost: 2, effort: 2 },
  { t: "Surf a famous break", cat: "adventure", cost: 2, effort: 2 },
  { t: "Climb a mountain", cat: "adventure", cost: 2, effort: 3 },
  { t: "Run a marathon", cat: "adventure", cost: 1, effort: 3 },
  { t: "Swim with dolphins", cat: "adventure", cost: 2, effort: 1 },
  { t: "Complete a multi-day thru-hike", cat: "adventure", cost: 1, effort: 3 },
  { t: "Try outdoor rock climbing", cat: "adventure", cost: 2, effort: 2 },
  { t: "Kayak through sea caves", cat: "adventure", cost: 2, effort: 2 },
  { t: "Sandboard down giant dunes", cat: "adventure", cost: 1, effort: 2 },
  { t: "Go whale watching", cat: "adventure", cost: 2, effort: 1 },
  { t: "Explore a cave system", cat: "adventure", cost: 1, effort: 2 },
  { t: "Try kitesurfing", cat: "adventure", cost: 2, effort: 3 },
  { t: "Ice-climb a glacier", cat: "adventure", cost: 3, effort: 3 },
  { t: "Run an ultramarathon", cat: "adventure", cost: 1, effort: 3 },
  { t: "Take a polar plunge", cat: "adventure", cost: 1, effort: 1 },
  { t: "Sail across an ocean", cat: "adventure", cost: 3, effort: 3 },
  // LEARN (21)
  { t: "Learn a new language to conversational level", cat: "learn", cost: 1, effort: 3 },
  { t: "Learn to play an instrument", cat: "learn", cost: 1, effort: 3 },
  { t: "Take a cooking class in another country", cat: "learn", cost: 2, effort: 1 },
  { t: "Learn photography", cat: "learn", cost: 1, effort: 2 },
  { t: "Take an introductory flying lesson", cat: "learn", cost: 2, effort: 1 },
  { t: "Learn to code and ship an app", cat: "learn", cost: 1, effort: 3 },
  { t: "Become a strong chess player", cat: "learn", cost: 1, effort: 2 },
  { t: "Learn pottery", cat: "learn", cost: 1, effort: 2 },
  { t: "Take a wine-tasting course", cat: "learn", cost: 2, effort: 1 },
  { t: "Learn sign language basics", cat: "learn", cost: 1, effort: 2 },
  { t: "Study the night sky with a telescope", cat: "learn", cost: 2, effort: 1 },
  { t: "Learn to dance (salsa or tango)", cat: "learn", cost: 1, effort: 2 },
  { t: "Write a novel", cat: "learn", cost: 1, effort: 3 },
  { t: "Learn calligraphy", cat: "learn", cost: 1, effort: 2 },
  { t: "Get first-aid / CPR certified", cat: "learn", cost: 1, effort: 1 },
  { t: "Master sourdough baking", cat: "learn", cost: 1, effort: 2 },
  { t: "Learn archery", cat: "learn", cost: 1, effort: 2 },
  { t: "Learn to sail", cat: "learn", cost: 2, effort: 2 },
  { t: "Take an improv comedy class", cat: "learn", cost: 1, effort: 1 },
  { t: "Learn woodworking", cat: "learn", cost: 2, effort: 2 },
  { t: "Study marine biology basics", cat: "learn", cost: 1, effort: 2 },
  // GIVE (21)
  { t: "Volunteer abroad for a month", cat: "give", cost: 2, effort: 3 },
  { t: "Donate blood regularly for a year", cat: "give", cost: 1, effort: 1 },
  { t: "Mentor a young person", cat: "give", cost: 1, effort: 2 },
  { t: "Plant 100 trees", cat: "give", cost: 1, effort: 2 },
  { t: "Run a charity fundraiser", cat: "give", cost: 1, effort: 2 },
  { t: "Help build homes with Habitat for Humanity", cat: "give", cost: 1, effort: 2 },
  { t: "Teach a skill for free", cat: "give", cost: 1, effort: 2 },
  { t: "Foster a rescue animal", cat: "give", cost: 1, effort: 2 },
  { t: "Organize a beach or park cleanup", cat: "give", cost: 1, effort: 2 },
  { t: "Donate your birthday to a charity", cat: "give", cost: 1, effort: 1 },
  { t: "Sponsor a child's education", cat: "give", cost: 2, effort: 1 },
  { t: "Start a small scholarship", cat: "give", cost: 2, effort: 2 },
  { t: "Volunteer weekly at a food bank for a year", cat: "give", cost: 1, effort: 2 },
  { t: "Donate hair to make wigs", cat: "give", cost: 1, effort: 1 },
  { t: "Organize a charity run", cat: "give", cost: 1, effort: 3 },
  { t: "Register as an organ donor", cat: "give", cost: 1, effort: 1 },
  { t: "Cook meals for a neighbor in need", cat: "give", cost: 1, effort: 1 },
  { t: "Donate professional skills pro-bono", cat: "give", cost: 1, effort: 2 },
  { t: "Start a community fridge", cat: "give", cost: 2, effort: 2 },
  { t: "Grant a stranger's wish anonymously", cat: "give", cost: 2, effort: 1 },
  { t: "Write thank-you letters to 50 people", cat: "give", cost: 1, effort: 1 },
  // CREATE (21)
  { t: "Publish a book", cat: "create", cost: 1, effort: 3 },
  { t: "Start a podcast", cat: "create", cost: 1, effort: 2 },
  { t: "Paint a mural", cat: "create", cost: 1, effort: 2 },
  { t: "Build a piece of furniture by hand", cat: "create", cost: 2, effort: 2 },
  { t: "Launch a small business", cat: "create", cost: 2, effort: 3 },
  { t: "Direct a short film", cat: "create", cost: 2, effort: 3 },
  { t: "Design a board game", cat: "create", cost: 1, effort: 2 },
  { t: "Record an album or EP", cat: "create", cost: 2, effort: 3 },
  { t: "Start a community garden", cat: "create", cost: 1, effort: 2 },
  { t: "Write a family cookbook", cat: "create", cost: 1, effort: 2 },
  { t: "Create a photo book of your travels", cat: "create", cost: 1, effort: 1 },
  { t: "Build a mobile app", cat: "create", cost: 1, effort: 3 },
  { t: "Start a YouTube channel", cat: "create", cost: 1, effort: 2 },
  { t: "Knit a blanket for someone", cat: "create", cost: 1, effort: 2 },
  { t: "Restore a classic car", cat: "create", cost: 3, effort: 3 },
  { t: "Choreograph a dance", cat: "create", cost: 1, effort: 2 },
  { t: "Write a song for someone you love", cat: "create", cost: 1, effort: 2 },
  { t: "Build a treehouse", cat: "create", cost: 2, effort: 2 },
  { t: "Make a short documentary", cat: "create", cost: 1, effort: 3 },
  { t: "Design your own tattoo", cat: "create", cost: 1, effort: 1 },
  { t: "Create a mobile game", cat: "create", cost: 1, effort: 3 }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { IDEA_CATEGORIES, CATEGORY_LABELS, IDEA_BANK };
}
